### PR TITLE
Change NEEDLES_DIR to working case

### PR DESCRIPTION
**Pull request by mimi1vx**
https://progress.opensuse.org/issues/131102
https://progress.opensuse.org/issues/127622

### CODE REVIEW

**Review by Martchus — APPROVED** [review]

**Comment by perlpunk** [comment]
But the test *is* currently working. How can that be explained?

**Comment by mimi1vx** [comment]
> But the test _is_ currently working. How can that be explained?

it takes some time when the product is scheduled to start test itself and some time is test in a running state before it fails... so the check can pass at this time without problems

**Comment by baierjan** [comment]
I  assume, this PR needs a rebase to benefit from https://github.com/os-autoinst/os-autoinst-distri-openQA/pull/127

**Review by okurz — APPROVED** [review]

**Comment by okurz** [comment]
@mimi1vx please rely on mergify and do not merge manually unless in rare exceptions but then please also explain what the reason for merging is.

**Pull request merged**
